// Code generated by nhatp.com/go/sugar/cmd/go-sugar - v0.1.0. DO NOT EDIT.

package example

func returnErrorOnly() error {
	if err := doSomething(); err != nil {
		return err
	}
	if err := doSomething(); err != nil {
		return err
	}

	return nil
}

func doSomething() error {
	return nil
}

// good
func newFunc() error {
	return nil
}
