package sugar

import (
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/mod/modfile"
	"golang.org/x/tools/go/packages"
)

const defaultBinary = "go-sugar"
const defaultVersion = "dev"
const defaultHeaderComment = "// Code generated by {binaryName} - {version}. DO NOT EDIT.\n\n"

func NewModule(path string, config Config, opts ...ModuleOption) (*Module, error) {
	env := config.env()
	info, err := os.Stat(path)
	if err != nil {
		return nil, err
	}

	var dir string
	if info.IsDir() {
		dir = path
	} else {
		dir = filepath.Dir(path)
	}

	// walk up to find go.mod
	root := dir
	for {
		goMod := filepath.Join(root, env.GoModFileName)
		if _, err := os.Stat(goMod); err == nil {
			break
		}
		parent := filepath.Dir(root)
		if parent == root {
			return nil, errors.New(env.GoModFileName + " not found")
		}
		root = parent
	}

	// read module path from go.mod
	goModPath := filepath.Join(root, env.GoModFileName)
	data, err := os.ReadFile(goModPath)
	if err != nil {
		return nil, err
	}
	pkgPath := modfile.ModulePath(data)
	if pkgPath == "" {
		return nil, errors.New("module path not found in " + env.GoModFileName)
	}

	mod := &Module{
		WorkingDir:    dir,
		Root:          root,
		GoModPath:     goModPath,
		PackagePath:   pkgPath,
		Config:        config,
		headerComment: defaultHeaderComment,
		binary:        defaultBinary,
		version:       defaultVersion,
		files:         make(map[string]*File),
	}
	for _, opt := range opts {
		opt.apply(mod)
	}

	if err = mod.DiscoverFiles(); err != nil {
		return nil, err
	}
	return mod, nil
}

type ModuleOption interface {
	apply(mod *Module)
}

type moduleOptionFunc func(mod *Module)

func (f moduleOptionFunc) apply(mod *Module) {
	f(mod)
}

func WithBinary(v string) ModuleOption {
	return moduleOptionFunc(func(mod *Module) {
		mod.binary = v
	})
}

func WithVersion(v string) ModuleOption {
	return moduleOptionFunc(func(mod *Module) {
		mod.version = v
	})
}

func WithHeaderComment(template string) ModuleOption {
	return moduleOptionFunc(func(mod *Module) {
		mod.headerComment = template
	})
}

// ---

type Module struct {
	WorkingDir    string
	Root          string
	GoModPath     string
	PackagePath   string
	Config        Config
	headerComment string
	binary        string
	version       string
	files         map[string]*File
}

func (m *Module) Files() map[string]*File {
	return m.files
}

func (m *Module) DiscoverFiles() error {
	targets, err := m.Resolve("./...")
	if err != nil {
		return err
	}
	fps, err := targets.Resolve()
	if err != nil {
		return err
	}

	for _, fp := range fps {
		_, err = m.RegisterFile(fp.RelPath)
		if err != nil {
			return err
		}
	}
	return nil
}

func (m *Module) RegisterFile(relPath string) (*File, error) {
	absPath := filepath.Join(m.Root, relPath)
	content, err := os.ReadFile(absPath)
	if err != nil {
		return nil, err
	}
	return m.AddFile(relPath, content)
}

func (m *Module) AddFile(relPath string, content []byte) (*File, error) {
	env := m.Config.env()
	ext := filepath.Ext(relPath)
	if !env.IsSugarFile(ext) {
		return nil, fmt.Errorf("unsupported file extension: %s", ext)
	}

	file := newFile(relPath, env.GoFilePath(relPath), content)
	m.files[relPath] = file
	return file, nil
}

func (m *Module) RemoveFile(relPath string) {
	delete(m.files, relPath)
}

func (m *Module) File(relPath string) (*File, bool) {
	f, ok := m.files[relPath]
	return f, ok
}

func (m *Module) HasFile(relPath string) bool {
	_, ok := m.files[relPath]
	return ok
}

func (m *Module) StructuralTransform() {
	for _, v := range m.files {
		v.StructuralTransform()
	}
}

func (m *Module) SemanticTransform() error {
	var fileErrors FileErrors
	m.StructuralTransform()

	if err := collectError(&fileErrors, m.analyzeSemantic()); err != nil {
		return err
	}

	for _, v := range m.files {
		v.SemanticTransform()
	}

	if len(fileErrors) > 0 {
		return fileErrors
	}
	return nil
}

// Generate performs generate pipeline for all managed Files
func (m *Module) Generate() (map[*File][]byte, error) {
	result := make(map[*File][]byte)
	var errs []error
	for _, f := range m.Files() {
		content, err := m.GenerateFile(f)
		if err != nil {
			errs = append(errs, err)
			continue
		}
		result[f] = content
	}
	return result, errors.Join(errs...)
}

// GenerateFile performs generate pipeline given File
func (m *Module) GenerateFile(file *File) ([]byte, error) {
	file.StructuralTransform()
	content, err := format.Source(file.SemanticTransform())
	if err != nil {
		return nil, err
	}
	return m.prependHeaderComment(content), nil
}

func (m *Module) GenerateOnDemand(relPath string, content []byte) (string, []byte, error) {
	env := m.Config.env()
	goFilePath := env.GoFilePath(relPath)

	f := newFile(relPath, goFilePath, content)
	generated, err := m.GenerateFile(f)
	if err != nil {
		return "", nil, err
	}
	return goFilePath, generated, nil
}

func (m *Module) FormatFile(file *File) ([]byte, error) {
	formatted, err := format.Source(file.StructuralTransform())
	if err != nil {
		return nil, err
	}
	return RestoreTransform(formatted), nil
}

func (m *Module) prependHeaderComment(content []byte) []byte {
	headerComment := m.headerComment
	if headerComment == "" {
		return content
	}

	header := strings.ReplaceAll(headerComment, "{binaryName}", m.binary)
	header = strings.ReplaceAll(header, "{version}", m.version)

	return append([]byte(header), content...)
}

func (m *Module) analyzeSemantic() error {
	var sugarFiles = make(map[string]*File)
	overlay := make(map[string][]byte)
	for p, f := range m.files {
		sugarFiles[p] = f
		fp := filepath.Join(m.Root, f.goPath)
		overlay[fp] = f.StructuralTransform()
	}

	cfg := &packages.Config{
		Mode:    packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedSyntax | packages.NeedDeps | packages.NeedImports,
		Fset:    token.NewFileSet(),
		Overlay: overlay,
		Dir:     m.Root,
	}
	pkgs, _ := packages.Load(cfg, "./...")
	for p, f := range sugarFiles {
		fpp := m.filePkgPath(p)

		var pkg *packages.Package
		for _, v := range pkgs {
			if fpp == v.ID {
				pkg = v
				break
			}
		}

		if pkg != nil {
			// not fail just because the semantic analysis fail
			_ = f.semanticAnalysis(pkg)
		}
	}
	return nil
}

func (m *Module) filePkgPath(relPath string) string {
	dir := filepath.Dir(relPath)
	if dir == "." {
		return m.PackagePath
	}
	return m.PackagePath + "/" + filepath.ToSlash(dir)
}

func (m *Module) Resolve(inputs ...string) (TargetCollection, error) {
	var result []Target
	for _, input := range inputs {
		if strings.HasSuffix(input, "/...") {
			dir := strings.TrimSuffix(input, "/...")
			p := filepath.Join(m.WorkingDir, dir)
			info, err := os.Stat(p)
			if err != nil {
				return nil, err
			}
			if !info.IsDir() {
				return nil, fmt.Errorf("%s is not a directory", p)
			}

			// recursive dir Target
			result = append(result, Target{
				Config:     m.Config,
				Root:       m.Root,
				WorkingDir: m.WorkingDir,
				Input:      input,

				Path:      p,
				IsDir:     true,
				Recursive: true,
			})
			continue
		}

		p := filepath.Join(m.WorkingDir, input)
		info, err := os.Stat(p)
		if err != nil {
			return nil, err
		}

		if info.IsDir() {
			// non recursive dir Target
			result = append(result, Target{
				Config:     m.Config,
				Root:       m.Root,
				WorkingDir: m.WorkingDir,
				Input:      input,

				Path:      p,
				IsDir:     true,
				Recursive: false,
			})
			continue
		}

		// add file Target
		result = append(result, Target{
			Config:     m.Config,
			Root:       m.Root,
			WorkingDir: m.WorkingDir,
			Input:      input,

			Path:      p,
			IsDir:     false,
			Recursive: false,
		})
	}
	return result, nil
}

var _ moduleAPI = (*Module)(nil)
